sudo: required

language: python

python:
  - '3.6'
  - '2.7'

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y parallel

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - make lint
  - make unit_tests
  - make integration_tests

notifications:
  email: false
