sudo: required

language: python

python:
  - '3.6'

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y parallel wget

install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.25.0/bazel-0.25.0-linux-x86_64
  - mkdir bin
  - mv bazel-0.25.0-linux-x86_64 bin/bazel
  - chmod u+x bin/bazel
  - pip install pip-tools

script:
  - PATH="$TRAVIS_BUILD_DIR/bin:$PATH" make check

notifications:
  email: false
