sudo: required

language: python
cache: pip

python:
  - '2.7'

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y parallel

install:
  - pip install pipenv
  - make install

script:
  - make lint
  - make unit_tests
  - make integration_tests
  - pipenv check

notifications:
  email: false
