sudo: required

language: python

python:
  - '3.6'

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y parallel wget

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y bazel
  - pip install pip-tools

script:
  - make check

notifications:
  email: false
